site_name: fast api
nav:
  - Home: index.md
  - API: api/index.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "^mkdocstrings_handlers"
          rendering:
            show_root_heading: true
            show_source: true
theme: readthedocs